export { default as msgContract } from './contractDetailMsg'
export { default as contractPay } from './contractDetailPay'
export { default as subContract } from './contractDetailSub'
export { default as partner } from './contractDetailPartner'
export { default as atta } from './contractDetailAtta'
export { default as goods } from './contractDetailGoods'
